import React, { useState } from 'react';
import { FileText, Download, Eye, Search, Plus, X, Loader, Brain } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { useAlerts } from '../hooks/useAlerts';
import { addReport } from '../services/alertService';
import { aiService } from '../services/aiService';
import './Reports.css';

const priorityClass = { critical: 'badge-red', high: 'badge-orange', medium: 'badge-blue', low: 'badge-gray' };
const statusClass = { open: 'badge-red', investigating: 'badge-orange', resolved: 'badge-green', closed: 'badge-gray' };

export default function Reports() {
  const { alerts } = useAlerts();

  const formatDate = (dateField, fallbackTime) => {
    try {
      if (dateField?.toDate) return dateField.toDate().toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
      if (typeof dateField === 'number' || typeof dateField === 'string') {
        const d = new Date(dateField);
        if (!isNaN(d.getTime())) return d.toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
      }
    } catch (e) {}
    return fallbackTime || '—';
  };
  
  const caseReports = alerts.map(a => ({
    id: a.id,
    title: a.type || a.emergencyType || 'Incident',
    type: a.type || a.emergencyType || 'General',
    officer: a.assignedOfficerName || a.officerName || a.officer || a.assignedOfficer || 'Unassigned',
    submittedAt: formatDate(a.createdAt, a.time),
    resolvedAt: formatDate(a.resolvedAt, null),
    priority: a.status === 'critical' ? 'critical' : a.status === 'resolved' ? 'low' : 'medium',
    status: a.status === 'resolved' ? 'resolved' : a.status === 'critical' ? 'open' : 'investigating'
  }));

  const [search, setSearch] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');
  const [showNew, setShowNew] = useState(false);
  const [loading, setLoading] = useState(false);
  const [selectedReport, setSelectedReport] = useState(null);
  
  // AI State
  const [aiAnalysis, setAiAnalysis] = useState('');
  const [analyzing, setAnalyzing] = useState(false);
  const [showAiModal, setShowAiModal] = useState(false);

  const [newReport, setNewReport] = useState({
    title: '', type: 'Crime', priority: 'medium', officer: '', description: ''
  });

  const handleAddReport = async () => {
    if (!newReport.title) return alert('Report title is required.');
    setLoading(true);
    try {
      await addReport({
        emergencyType: newReport.title, // Title maps to type for alerts
        type: newReport.type,
        assignedOfficer: newReport.officer,
        description: newReport.description,
        status: newReport.priority === 'critical' ? 'critical' : 'medium'
      });
      setShowNew(false);
      setNewReport({ title: '', type: 'Crime', priority: 'medium', officer: '', description: '' });
    } catch (e) {
      alert('Error creating report: ' + e.message);
    }
    setLoading(false);
  };

  const filtered = caseReports.filter(r => {
    const matchStatus = filterStatus === 'all' || r.status === filterStatus;
    const matchSearch = r.title.toLowerCase().includes(search.toLowerCase()) ||
      r.id.toLowerCase().includes(search.toLowerCase()) ||
      r.officer.toLowerCase().includes(search.toLowerCase());
    return matchStatus && matchSearch;
  });

  const handleAiAnalysis = async () => {
    if (filtered.length === 0) return alert("No reports to analyze.");
    setAnalyzing(true);
    setShowAiModal(true);
    try {
      const summary = await aiService.analyzeReports(filtered);
      setAiAnalysis(summary);
    } catch (e) {
      setAiAnalysis("Error generating analysis. Make sure VITE_GEMINI_API_KEY is configured correctly.\n\n" + e.message);
    }
    setAnalyzing(false);
  };

  const handleDownload = (report) => {
    const text = `CASE REPORT: ${report.id}\nTitle: ${report.title}\nType: ${report.type}\nStatus: ${report.status}\nPriority: ${report.priority}\nOfficer: ${report.officer}\nSubmitted At: ${report.submittedAt}\nResolved At: ${report.resolvedAt}\n\nGenerated by SERS System`;
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Report_${report.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="reports-page">
      <div className="page-header">
        <div>
          <h1 className="page-title">Case Reports</h1>
          <p className="page-sub">{caseReports.length} total reports · {caseReports.filter(r => r.status === 'open').length} open</p>
        </div>
        <div className="header-actions">
          <button className="btn btn-ghost btn-sm" onClick={handleAiAnalysis} disabled={analyzing}>
            {analyzing ? <Loader size={14} className="spin-icon" /> : <Brain size={14} style={{ color: '#9b59b6' }} />} AI Analyze
          </button>
          <button className="btn btn-ghost btn-sm" onClick={() => handleDownload(filtered[0] || caseReports[0])}><Download size={14} /> Export All</button>
          <button className="btn btn-primary btn-sm" id="new-report-btn" onClick={() => setShowNew(true)}>
            <Plus size={14} /> New Report
          </button>
        </div>
      </div>

      {/* Report Stats */}
      <div className="report-stats">
        {[
          { label: 'Open', count: caseReports.filter(r => r.status === 'open').length, badge: 'badge-red' },
          { label: 'Investigating', count: caseReports.filter(r => r.status === 'investigating').length, badge: 'badge-orange' },
          { label: 'Resolved', count: caseReports.filter(r => r.status === 'resolved').length, badge: 'badge-green' },
          { label: 'Closed', count: caseReports.filter(r => r.status === 'closed').length, badge: 'badge-gray' },
        ].map(s => (
          <div key={s.label} className="card report-stat">
            <span className={`badge ${s.badge}`} style={{ fontSize: '0.9rem', padding: '4px 12px' }}>{s.label}</span>
            <div style={{ fontSize: '2rem', fontWeight: 900, color: 'var(--text-primary)', marginTop: 8 }}>{s.count}</div>
          </div>
        ))}
      </div>

      {/* Toolbar */}
      <div className="card alerts-toolbar">
        <div className="search-wrap" style={{ maxWidth: 340 }}>
          <Search size={15} />
          <input type="text" placeholder="Search reports…" value={search} onChange={e => setSearch(e.target.value)} />
        </div>
        <div className="filter-tabs">
          {['all', 'open', 'investigating', 'resolved', 'closed'].map(f => (
            <button key={f} className={`filter-tab ${filterStatus === f ? 'active' : ''}`} onClick={() => setFilterStatus(f)}>
              {f === 'all' ? 'All' : f.charAt(0).toUpperCase() + f.slice(1)}
            </button>
          ))}
        </div>
      </div>

      {/* Table */}
      <div className="card table-card">
        <div className="table-wrap">
          <table className="alerts-table">
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Title</th>
                <th>Type</th>
                <th>Officer</th>
                <th>Submitted At</th>
                <th>Resolved At</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map(r => (
                <tr key={r.id} className="table-row">
                  <td><span className="incident-id">{r.id}</span></td>
                  <td style={{ fontWeight: 600, maxWidth: 220 }}>{r.title}</td>
                  <td><span className="type-chip">{r.type}</span></td>
                  <td style={{ color: 'var(--text-secondary)' }}>{r.officer}</td>
                  <td style={{ color: 'var(--text-muted)', fontSize: '0.82rem' }}>{r.submittedAt}</td>
                  <td style={{ color: 'var(--text-muted)', fontSize: '0.82rem' }}>{r.resolvedAt}</td>
                  <td><span className={`badge ${priorityClass[r.priority]}`}>{r.priority}</span></td>
                  <td><span className={`badge ${statusClass[r.status]}`}>{r.status}</span></td>
                  <td>
                    <div className="action-btns">
                      <button className="btn btn-ghost btn-sm" onClick={() => setSelectedReport(r)}><Eye size={13} /> View</button>
                      <button className="btn btn-ghost btn-sm" onClick={() => handleDownload(r)}><Download size={13} /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {showNew && (
        <div className="modal-overlay" onClick={() => setShowNew(false)}>
          <div className="modal-box" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>New Case Report</h3>
              <button className="modal-close" onClick={() => setShowNew(false)}><X size={14} /></button>
            </div>
            <div className="modal-body">
              <div className="add-form">
                <div className="form-group"><label>Report Title</label><input type="text" placeholder="Brief incident description" value={newReport.title} onChange={e => setNewReport({...newReport, title: e.target.value})} /></div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
                  <div className="form-group"><label>Type</label>
                    <select value={newReport.type} onChange={e => setNewReport({...newReport, type: e.target.value})}><option>Crime</option><option>Traffic</option><option>Domestic</option><option>Narcotics</option><option>Missing</option><option>Accident</option></select>
                  </div>
                  <div className="form-group"><label>Priority</label>
                    <select value={newReport.priority} onChange={e => setNewReport({...newReport, priority: e.target.value})}><option>critical</option><option>high</option><option>medium</option><option>low</option></select>
                  </div>
                </div>
                <div className="form-group"><label>Assigned Officer</label><input type="text" placeholder="Officer name" value={newReport.officer} onChange={e => setNewReport({...newReport, officer: e.target.value})} /></div>
                <div className="form-group"><label>Description</label><textarea rows={4} placeholder="Detailed incident description…" style={{ resize: 'vertical' }} value={newReport.description} onChange={e => setNewReport({...newReport, description: e.target.value})} /></div>
              </div>
            </div>
            <div className="modal-footer">
              <button className="btn btn-ghost" onClick={() => setShowNew(false)} disabled={loading}>Cancel</button>
              <button className="btn btn-primary" onClick={handleAddReport} disabled={loading}>
                {loading ? <Loader size={14} className="spin-icon" /> : <Plus size={14} />} Submit Report
              </button>
            </div>
          </div>
        </div>
      )}

      {/* View Report Modal */}
      {selectedReport && (
        <div className="modal-overlay" onClick={() => setSelectedReport(null)}>
          <div className="modal-box" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Report Details: {selectedReport.id.substring(0, 8)}</h3>
              <button className="modal-close" onClick={() => setSelectedReport(null)}><X size={14} /></button>
            </div>
            <div className="modal-body">
              <div style={{ marginBottom: 16 }}>
                <span className={`badge ${statusClass[selectedReport.status]}`}>{selectedReport.status}</span>
                <span className={`badge ${priorityClass[selectedReport.priority]}`} style={{ marginLeft: 8 }}>{selectedReport.priority}</span>
              </div>
              <div className="detail-grid">
                <div><label>Title</label><p>{selectedReport.title}</p></div>
                <div><label>Type</label><p>{selectedReport.type}</p></div>
                <div><label>Officer</label><p>{selectedReport.officer}</p></div>
                <div><label>Submitted At</label><p>{selectedReport.submittedAt}</p></div>
                <div><label>Resolved At</label><p>{selectedReport.resolvedAt}</p></div>
              </div>
            </div>
            <div className="modal-footer">
              <button className="btn btn-ghost" onClick={() => handleDownload(selectedReport)}><Download size={14} /> Download PDF</button>
              <button className="btn btn-primary" onClick={() => setSelectedReport(null)}>Close</button>
            </div>
          </div>
        </div>
      )}

      {/* AI Analysis Modal */}
      {showAiModal && (
        <div className="modal-overlay" onClick={() => setShowAiModal(false)}>
          <div className="modal-box" onClick={e => e.stopPropagation()} style={{ maxWidth: 600 }}>
            <div className="modal-header">
              <h3 style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <Brain size={16} style={{ color: '#9b59b6' }} /> Gemini Intelligence Report
              </h3>
              <button className="modal-close" onClick={() => setShowAiModal(false)}><X size={14} /></button>
            </div>
            <div className="modal-body" style={{ minHeight: 150 }}>
              {analyzing ? (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '40px 0', color: 'var(--text-muted)' }}>
                  <Loader size={32} className="spin-icon" style={{ marginBottom: 16, color: '#9b59b6' }} />
                  <p>Analyzing {filtered.length} reports with Gemini AI...</p>
                </div>
              ) : (
                <div style={{ padding: 10, lineHeight: 1.6, fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                  <ReactMarkdown>{aiAnalysis}</ReactMarkdown>
                </div>
              )}
            </div>
            <div className="modal-footer">
              <button className="btn btn-primary" onClick={() => setShowAiModal(false)}>Acknowledge</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
